import { CountryInfo } from "@/types/assessment";

export const SUPPORTED_COUNTRIES: CountryInfo[] = [
  {
    id: "india",
    name: "India",
    region: "Asia-Pacific",
    currency_code: "INR",
    currency_symbol: "₹",
    usd_exchange_rate: 83.0,
    grid_co2e_per_kwh: 0.827,
    grid_tariff_usd_per_kwh: 0.09,
    natural_gas_usd_per_m3: 0.45,
    diesel_usd_per_litre: 1.10,
    coal_usd_per_kg: 0.12,
    capex_regional_multiplier: 0.60,
    carbon_tax_usd_per_tco2e: 0.0,
    flag_emoji: "🇮🇳",
  },
  {
    id: "usa",
    name: "United States",
    region: "North America",
    currency_code: "USD",
    currency_symbol: "$",
    usd_exchange_rate: 1.0,
    grid_co2e_per_kwh: 0.385,
    grid_tariff_usd_per_kwh: 0.14,
    natural_gas_usd_per_m3: 0.30,
    diesel_usd_per_litre: 1.05,
    coal_usd_per_kg: 0.08,
    capex_regional_multiplier: 1.00,
    carbon_tax_usd_per_tco2e: 0.0,
    flag_emoji: "🇺🇸",
  },
  {
    id: "eu_germany",
    name: "Germany (EU)",
    region: "Europe",
    currency_code: "EUR",
    currency_symbol: "€",
    usd_exchange_rate: 0.92,
    grid_co2e_per_kwh: 0.350,
    grid_tariff_usd_per_kwh: 0.22,
    natural_gas_usd_per_m3: 0.70,
    diesel_usd_per_litre: 1.80,
    coal_usd_per_kg: 0.18,
    capex_regional_multiplier: 1.15,
    carbon_tax_usd_per_tco2e: 85.0,
    flag_emoji: "🇩🇪",
  },
  {
    id: "uk",
    name: "United Kingdom",
    region: "Europe",
    currency_code: "GBP",
    currency_symbol: "£",
    usd_exchange_rate: 0.79,
    grid_co2e_per_kwh: 0.207,
    grid_tariff_usd_per_kwh: 0.25,
    natural_gas_usd_per_m3: 0.65,
    diesel_usd_per_litre: 1.75,
    coal_usd_per_kg: 0.16,
    capex_regional_multiplier: 1.10,
    carbon_tax_usd_per_tco2e: 65.0,
    flag_emoji: "🇬🇧",
  },
  {
    id: "china",
    name: "China",
    region: "Asia-Pacific",
    currency_code: "CNY",
    currency_symbol: "¥",
    usd_exchange_rate: 7.20,
    grid_co2e_per_kwh: 0.570,
    grid_tariff_usd_per_kwh: 0.10,
    natural_gas_usd_per_m3: 0.50,
    diesel_usd_per_litre: 1.15,
    coal_usd_per_kg: 0.10,
    capex_regional_multiplier: 0.65,
    carbon_tax_usd_per_tco2e: 12.0,
    flag_emoji: "🇨🇳",
  },
  {
    id: "japan",
    name: "Japan",
    region: "Asia-Pacific",
    currency_code: "JPY",
    currency_symbol: "¥",
    usd_exchange_rate: 150.0,
    grid_co2e_per_kwh: 0.435,
    grid_tariff_usd_per_kwh: 0.20,
    natural_gas_usd_per_m3: 0.80,
    diesel_usd_per_litre: 1.30,
    coal_usd_per_kg: 0.15,
    capex_regional_multiplier: 1.05,
    carbon_tax_usd_per_tco2e: 25.0,
    flag_emoji: "🇯🇵",
  },
  {
    id: "global_default",
    name: "Global Baseline",
    region: "Global",
    currency_code: "USD",
    currency_symbol: "$",
    usd_exchange_rate: 1.0,
    grid_co2e_per_kwh: 0.475,
    grid_tariff_usd_per_kwh: 0.12,
    natural_gas_usd_per_m3: 0.40,
    diesel_usd_per_litre: 1.20,
    coal_usd_per_kg: 0.12,
    capex_regional_multiplier: 1.00,
    carbon_tax_usd_per_tco2e: 0.0,
    flag_emoji: "🌐",
  },
];

export function getCountryById(countryId: string): CountryInfo {
  const norm = countryId?.toLowerCase().trim();
  return (
    SUPPORTED_COUNTRIES.find((c) => c.id === norm) ||
    SUPPORTED_COUNTRIES.find((c) => c.id === "global_default")!
  );
}
